version: '3.6'

networks:
    guacamole-network:
        driver: bridge 

services:
    guacd: 
        image: guacamole/guacd
        networks:
            guacamole-network:
        restart: always
        
    postgres:
        environment: 
            PGDATA: /var/lib/posgtgresql/data/guacamole
            POSTGRES_DB: guac_db
            POSTGRES_PASSWORD: letmein123 # TODO: Implement this with Docker Secrets
            POSTGRES_USER: guacamole_user
        image: postgres
        networks:
            guacamole-network:
        restart: always
        volumes:
            - ./init:/docker-entrypoint-initdb.d:ro
            - ./data:/var/lib/postgresql/data:rw

    guacamole-webapp:
        depends_on: 
            - guacd
            - postgres
        environment: 
            # GUAC_LOG_LEVEL: debug # this is helpful for troubleshooting
            GUACD_HOSTNAME: guacd
            POSTGRES_DATABASE: guac_db
            POSTGRES_HOSTNAME: postgres
            POSTGRES_PASSWORD: letmein123
            POSTGRES_USER: guacamole_user
        image: guacamole/guacamole
        links:
            - guacd
            - postgres
        networks:
            guacamole-network:
        ports:
           - 8080:8080/tcp
        restart: always

    guacamole-webapp-2:
        depends_on: 
            - guacd
            - postgres
        environment: 
            # GUAC_LOG_LEVEL: debug # this is helpful for troubleshooting
            GUACD_HOSTNAME: guacd
            POSTGRES_DATABASE: guac_db
            POSTGRES_HOSTNAME: postgres
            POSTGRES_PASSWORD: letmein123
            POSTGRES_USER: guacamole_user
        image: guacamole/guacamole
        links:
            - guacd
            - postgres
        networks:
            guacamole-network:
        ports:
           - 8081:8080/tcp
        restart: always


        
