version: '3.6'

networks:
    guacamole-network:
        driver: bridge 

services:
    guacd: 
        image: guacamole/guacd
        networks:
            guacamole-network:
        restart: always
        volumes:
            - ./drive:/drive:rw # Not really sure what this is for 
            - ./record:/record:rw # Not really sure what this is for

    postgres:
        environment: 
            PGDATA: /var/lib/posgtgresql/data/guacamole
            POSTGRES_DB: guac_db
            POSTGRES_PASSWORD: letmein123 # TODO: Implement this with Docker Secrets
            POSTGRES_USER: guacamole_user
        image: postgres
        networks:
            guacamole-network:
        restart: always
        volumes:
            - ./init:/docker-entrypoint-initdb.d:ro
            - ./data:/var/lib/postgresql/data:rw

    guacamole-webapp:
        depends_on: 
            - guacd
            - postgres
        environment: 
            GUACD_HOSTNAME: guacd
            POSTGRES_DATABASE: guacamole_db
            POSTGRES_HOSTNAME: postgres
            POSTGRES_PASSWORD: letmein123
            POSTGRES_USER: guacamole_user
        image: guacamole/guacamole
        links:
            - guacd
            # -postgres #I feel like this is needed
        networks:
            guacamole-network:
        ports:
           - 8080:8080/tcp
        restart: always

        
