version: "3"

networks:
  monitoring_network:

services:
    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        ports:
            - 3000:3000
        networks:
            - monitoring_network
        volumes:
            - grafana-volume:/var/lib/grafana

    influxdb:
        #image: influxdb
        build: .
        container_name: influxdb_container
        restart: always
        ports:
            - 8086:8086
            - 8089:8089/udp
        networks:
          - monitoring_network
        volumes:
          - influxdb-volume:/var/lib/influxdb
volumes:
    grafana-volume:
        external: true
    influxdb-volume:
        external: true